Repository liquality/wav-game, pull requests merged in 2023-07, with the labels that each got.

#73 Fix/level 6 card
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/ChooseNewArtist/GameIncentives.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/GameCards/Level2.jsx
  frontend/src/components/GameCards/Level3.jsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/images/nft-squares.svg
  frontend/src/pages/Artist/Artist.jsx
Labels: 🔍 Ready for Review, size/L

#75 fix: resolve bug causing nft send to happen repeatedly
  frontend/src/components/Send/ProcessingSend.js
Labels: size/XS, 🔍 Ready for Review

#76 fix: fix issues with trade success and type errors
  backend/v1/services/contractService.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Send/SendStart.js
  frontend/src/components/Trade/TradeSuccess.js
  frontend/src/services/ContractService.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/M

#77 fix: update how nfts are fetched
  frontend/src/App.js
  frontend/src/components/Trade/TradeSuccess.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/services/ContractService.js
Labels: 🔍 Ready for Review, size/M

#78 fix: update get nfts
  frontend/src/App.js
  frontend/src/components/Send/SendStart.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/services/ContractService.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/M

#81 fix: create contractInstance if undefined
  frontend/src/services/ContractService.js
Labels: 🔍 Ready for Review, size/L

#83 update wallet-sdk version
  frontend/package-lock.json
  frontend/package.json
Labels: size/XS, 🔍 Ready for Review

#84 update wallet-sdk version
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Trade/TradeStart.js
Labels: size/XS, 🔍 Ready for Review

#86 Fix/UI fixes
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/button.css
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/GameTabs/GameTabs.tsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/images/won-card-bg.svg
  frontend/src/pages/Artist/Artist.jsx
Labels: 🔍 Ready for Review, size/L

#88 Feat/level 6 winner
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/images/Artist/Winner Full set banner.svg
  frontend/src/images/won-card-bg.svg
  frontend/src/services/ContractService.js
Labels: 🔍 Ready for Review, size/L

#89 Dev
  frontend/public/index.html
  frontend/src/components/Button/button.css
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/components/Send/PrepareSend.js
  frontend/src/images/Artist/Winner Full set banner.svg
  frontend/src/images/won-card-bg.svg
  frontend/src/pages/Home.js
  frontend/src/services/ContractService.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#90 fix regression - mint function
  blockchain/.gitignore
  blockchain/contracts/WavNFT.sol
  blockchain/hardhat.config.ts
  blockchain/package-lock.json
  blockchain/package.json
  blockchain/typechain-types/factories/contracts/WavGame__factory.ts
  blockchain/typechain-types/factories/contracts/WavNFT__factory.ts
Labels: 🔍 Ready for Review, size/S
