Repository liquality/wav-game, pull requests merged in 2023-06, with the labels that each got.

#14 Feature/dashboard
  backend/.nvmrc
  backend/package-lock.json
  backend/package.json
  frontend/src/App.js
  frontend/src/components/Footer.js
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/data/artitsts.json
  frontend/src/pages/Artist/Artist.tsx
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/pages/Artist/UserMenu.js
  frontend/src/pages/Artist/artist.css
  frontend/src/pages/Dashboard/Dashboard.tsx
  frontend/src/pages/Dashboard/LevelCard.tsx
  frontend/src/pages/Home.js
  frontend/src/services/ArtistService.js
Labels: ✅ Approved, size/XL

#16 new animation on progressbar
  frontend/src/App.css
  frontend/src/components/Navbar.js
  frontend/src/components/ProcessingTx.js
  frontend/src/components/Trade/ProcessingTrade.js
  frontend/src/components/Trade/TradeStart.js
Labels: 🔍 Ready for Review, size/M

#17 Feat/burn
  frontend/src/App.css
  frontend/src/components/Button.js
  frontend/src/components/Onboarding/LogInOrRegister.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/components/Onboarding/PickAvatar.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Dashboard/Dashboard.tsx
Labels: 🔍 Ready for Review, size/L

#19 Feat/leaderboard
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/images/full_abi.json
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/artist.css
Labels: 🔍 Ready for Review, size/XXL

#22 Feat/leaderboard
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Send/NftImages.js
  frontend/src/components/Send/PrepareSend.js
  frontend/src/components/Send/ProcessingSend.js
  frontend/src/components/Send/SendModal.js
  frontend/src/components/Send/SendStart.js
  frontend/src/components/Trade/ProcessingTrade.js
  frontend/src/images/full_abi.json
  frontend/src/images/polygon.svg
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/XXL

#21 Feature/dashboard
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/button.css
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/game-cards.css
  frontend/src/components/GameTabs/GameTabs.tsx
  frontend/src/components/GameTabs/game-tabs.css
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/components/LevelTab/LevelTab.tsx
  frontend/src/components/LevelTab/level-tab.css
  frontend/src/components/SpinningLoader.js
  frontend/src/data/artists.json
  frontend/src/data/levels.json
  frontend/src/images/card-bg-active.svg
  frontend/src/images/card-bg-off.svg
  frontend/src/images/lock_icon.svg
  frontend/src/images/won-card-bg.svg
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/artist.css
  frontend/src/pages/Home.js
  frontend/src/services/ArtistService.js
  frontend/src/services/StaticDataService.js
  frontend/src/stories/Button.stories.tsx
  frontend/src/stories/GameCards.stories.tsx
  frontend/src/stories/GameTabs.stories.tsx
  frontend/src/stories/LevelCard.stories.tsx
  frontend/src/stories/LevelTab.stories.tsx
  frontend/src/types/ButtonMode.ts
  frontend/src/types/LevelStatus.ts
Labels: 🔍 Ready for Review, size/XXL

#23 Feat/configure crossmint
  backend/sql/create.sql
  backend/v1/classes/Game.js
  frontend/README.md
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ArtistGrid.js
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/components/ProcessingTx.js
  frontend/src/components/Send/PrepareSend.js
  frontend/src/components/Send/SendStart.js
  frontend/src/components/Trade/ProcessingTrade.js
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/data/contract_data.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/XXL

#24 Feat/artist grid logic
  frontend/build-storybook.log
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ArtistGrid.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/game-cards.css
  frontend/src/components/GameTabs/GameTabs.tsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/data/artists.json
  frontend/src/images/artist.png
  frontend/src/images/artists/abjo.jpg
  frontend/src/images/artists/black-dave.jpg
  frontend/src/images/artists/cam-murdoch.jpg
  frontend/src/images/artists/fred-riko.jpg
  frontend/src/images/artists/jadyn-violet.jpg
  frontend/src/images/artists/karma-violetta.jpg
  frontend/src/images/artists/tarot.jpg
  frontend/src/images/artists/tk.jpg
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/pages/Home.js
  frontend/src/services/StaticDataService.js
Labels: 🔍 Ready for Review, size/XL

#25 Feat/usermenu interaction
  backend/v1/classes/Game.js
  backend/v1/endpoints.js
  backend/v1/handlers/gameHandler.js
  frontend/src/components/ArtistGrid.js
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/ChooseNewArtist/GameIncentives.js
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/UserMenu.js
  frontend/src/services/UserService.js
Labels: size/L

#26 Feature/artist level data
  backend/v1/classes/User.js
  frontend/.gitignore
  frontend/build-storybook.log
  frontend/config-overrides.js
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/DataContext.ts
  frontend/src/components/ArtistGrid.js
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/Footer.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/data/artists.json
  frontend/src/images/instagram.svg
  frontend/src/images/lens.svg
  frontend/src/images/tiktok.svg
  frontend/src/index.tsx
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/pages/Artist/UserMenu.js
  frontend/src/services/StaticDataService.js
Labels: ✅ Approved, size/XL

#29 Feat/send metadata
  backend/package-lock.json
  backend/v1/classes/Game.js
  backend/v1/classes/User.js
  backend/v1/endpoints.js
  backend/v1/handlers/gameHandler.js
  frontend/src/App.css
  frontend/src/components/Onboarding/LogInOrRegister.js
  frontend/src/components/Onboarding/PickAvatar.js
  frontend/src/components/Send/NftImages.js
  frontend/src/components/Send/PrepareSend.js
  frontend/src/components/Send/SendStart.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/services/UserService.js
Labels: 🔍 Ready for Review, size/XL

#28 feat: sponsor gas for leveling up tx
  .gitignore
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Send/PrepareSend.js
  frontend/src/components/Send/SendStart.js
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/data/contract_data.js
  package-lock.json
Labels: 🔍 Ready for Review, size/XXL

#30 fix: add missing await
  frontend/.env.example
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
Labels: ✅ Approved, size/S

#27 Update contract logic
  blockchain/.openzeppelin/polygon-mumbai.json
  blockchain/contracts/WavGame.sol
  blockchain/contracts/WavNFT.sol
  blockchain/deploy/00_deploy_wav_game.ts
  blockchain/package-lock.json
  blockchain/package.json
  blockchain/test/wavGame.ts
  blockchain/typechain-types/contracts/WavGame.ts
  blockchain/typechain-types/contracts/WavNFT.ts
  blockchain/typechain-types/factories/contracts/WavGame__factory.ts
  blockchain/typechain-types/factories/contracts/WavNFT__factory.ts
Labels: 🔍 Ready for Review, size/XL

#33 Feat/calculate nfts
  frontend/src/components/ArtistGrid.js
  frontend/src/components/LevelTab/LevelTab.tsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/UserMenu.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#34 feat: added card logic to display content and colors depending of the…
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/GameCards/Level2.jsx
  frontend/src/components/GameCards/Level3.jsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/pages/Artist/Artist.jsx
Labels: ✅ Approved, size/L

#35 Fix/update contract naming
  blockchain/.eslintrc.js
  blockchain/.gitignore
  blockchain/.prettierignore
  blockchain/.prettierrc
  blockchain/.solhint.json
  blockchain/.solhintignore
  blockchain/README.md
  blockchain/contracts/WavGame.sol
  blockchain/contracts/WavNFT.sol
  blockchain/contracts/interfaces/IWavGame.sol
  blockchain/contracts/interfaces/IWavNFT.sol
  blockchain/contracts/libraries/Helper.sol
  blockchain/deploy/00_deploy_wav_game.ts
  blockchain/hardhat.config.ts
  blockchain/package-lock.json
  blockchain/package.json
  blockchain/test/wavGame.ts
  blockchain/typechain-types/contracts/WavGame.ts
  blockchain/typechain-types/contracts/interfaces/IWavGame.ts
  blockchain/typechain-types/factories/contracts/WavGame__factory.ts
  blockchain/typechain-types/factories/contracts/WavNFT__factory.ts
  blockchain/typechain-types/factories/contracts/interfaces/IWavGame__factory.ts
Labels: ✅ Approved, size/XXL

#36 Feat/logic choose artist
  backend/v1/classes/Game.js
  backend/v1/handlers/gameHandler.js
  backend/v1/helper.js
  frontend/src/components/ArtistGrid.js
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/components/Send/PrepareSend.js
  frontend/src/data/artists.json
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/stories/GameCards.stories.tsx
Labels: 🔍 Ready for Review, size/L

#38 Feat/card levels
  backend/sql/create.sql
  backend/v1/classes/Game.js
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#39 feat: set won status for level 6
  frontend/src/components/GameCards/Level6.jsx
Labels: 🔍 Ready for Review, size/M

#40 - Added upsert for new users
  backend/sql/create.sql
  backend/v1/classes/User.js
  frontend/src/components/Home/HomeNotSignedIn.js
  frontend/src/components/Modal.js
  frontend/src/components/Onboarding/PickAvatar.js
  frontend/src/pages/Home.js
Labels: 🔍 Ready for Review, size/XL

#41 Fix/dwav 69 get more button to artist page
  frontend/src/App.js
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/ChooseNewArtist/GameIncentives.js
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/pages/Artist/UserMenu.js
Labels: 🔍 Ready for Review, size/M

#42 fix: correct copytext in 'how to' module on homepage
  frontend/src/components/Navbar.js
  frontend/src/pages/Home.js
Labels: 🔍 Ready for Review, size/S

#43 fix: put back tk artist data, fixed nav bar issues
  frontend/src/components/Navbar.js
  frontend/src/data/artists.json
Labels: 🔍 Ready for Review, size/S

#37 fix: style & test fixes
  blockchain/hardhat.config.ts
  blockchain/test/wavGame.ts
  blockchain/tsconfig.json
Labels: 🔍 Ready for Review, size/L

#47 Fix nftCount issues and trade errors
  blockchain/typechain-types/contracts/WavGame.ts
  blockchain/typechain-types/factories/contracts/WavGame__factory.ts
  blockchain/typechain-types/factories/contracts/WavNFT__factory.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/GameCards/Level2.jsx
  frontend/src/components/GameCards/Level3.jsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameTabs/GameTabs.tsx
  frontend/src/components/ProcessingTx.js
  frontend/src/components/Trade/ProcessingTrade.js
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/data/contract_data.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/services/contractService.js
  frontend/src/utils.ts
Labels: ✅ Approved, size/XL

#45 fix: set logic to validate session and apply choose an artist modal flow
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/ArtistGrid.js
  frontend/src/components/Button/button.css
  frontend/src/components/ChooseNewArtist/ChooseNewArtistModal.js
  frontend/src/components/Footer.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/Modal.js
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/components/Onboarding/PickAvatar.js
  frontend/src/images/lens.svg
  frontend/src/images/lenster.png
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/pages/Home.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#48 Feat/johanna linear
  frontend/src/App.css
  frontend/src/components/Faq.js
  frontend/src/components/Footer.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/artist.css
Labels: 🔍 Ready for Review, size/L

#50 Feat/johanna linear
  backend/v1/classes/Game.js
  backend/v1/classes/User.js
  frontend/.env.example
  frontend/src/App.css
  frontend/src/components/ArtistGrid.js
  frontend/src/components/Modal.js
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/components/Onboarding/PickAvatar.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/images/powered_by_crossmintPNG.png
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/UserMenu.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#52 fix: fix nft count
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#54 fixed env value for explorer
  frontend/.env.example
  frontend/src/components/Trade/TradeStart.js
Labels: size/XS, 🔍 Ready for Review

#55 fix minor typeError with levelUp
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
Labels: 🔍 Ready for Review, size/S

#56 fix: validate the contract creation to not initialize all the time
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
Labels: size/S

#58 Feat/testing bugs
  backend/v1/classes/User.js
  frontend/src/App.js
  frontend/src/DataContext.js
  frontend/src/DataContext.ts
  frontend/src/components/Faq.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/Modal.js
  frontend/src/components/Trade/TradeModal.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Leaderboard.js
  frontend/src/pages/Artist/UserMenu.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#59 Feat/testing bugs
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/UserMenu.js
Labels: 🔍 Ready for Review, size/S

#60 Feat/count down settings from db
  backend/sql/level_setting.sql
  backend/v1/classes/LevelSetting.js
  backend/v1/endpoints.js
  backend/v1/handlers/gameHandler.js
  frontend/src/App.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/services/UserService.js
Labels: 🔍 Ready for Review, size/L

#62 Fix/copy tickets
  frontend/src/App.css
  frontend/src/components/Button/button.css
  frontend/src/components/GameCards/Level1.jsx
  frontend/src/components/GameCards/Level2.jsx
  frontend/src/components/GameCards/Level3.jsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/components/LevelTab/level-tab.css
  frontend/src/components/Onboarding/LogInOrRegister.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/data/artists.json
  frontend/src/index.css
  frontend/src/pages/Artist/Artist.jsx
  frontend/src/pages/Artist/Sidebar.tsx
  frontend/src/pages/Artist/artist.css
  frontend/src/pages/Home.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/L

#63 Move burn logic to backend
  backend/config.json
  backend/package-lock.json
  backend/package.json
  backend/sql/create.sql
  backend/v1/classes/Burn.js
  backend/v1/classes/Game.js
  backend/v1/classes/User.js
  backend/v1/endpoints.js
  backend/v1/handlers/gameHandler.js
  backend/v1/handlers/userHandler.js
  backend/v1/services/contractService.js
  blockchain/deploy/00_deploy_wav_game.ts
  blockchain/hardhat.config.ts
  blockchain/tsconfig.json
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/Trade/TradeStart.js
  frontend/src/services/UserService.js
  frontend/src/services/contractService.js
  frontend/src/utils.ts
Labels: 🔍 Ready for Review, size/XXL

#65 fix: update contracts
  backend/config.json
  backend/v1/services/contractService.js
  blockchain/.openzeppelin/polygon-mumbai.json
  blockchain/.openzeppelin/polygon.json
  blockchain/contracts/WavGame.sol
  blockchain/contracts/WavNFT.sol
  blockchain/contracts/interfaces/IWavGame.sol
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Trade/TradeStart.js
  frontend/src/data/contract_data.js
Labels: 🔍 Ready for Review, size/XXL

#67 display earlybird count on level card
  blockchain/typechain-types/contracts/WavGame.ts
  blockchain/typechain-types/contracts/WavNFT.ts
  blockchain/typechain-types/factories/contracts/WavGame__factory.ts
  blockchain/typechain-types/factories/contracts/WavNFT__factory.ts
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/Trade/TradeStart.js
  frontend/src/services/ContractService.js
Labels: 🔍 Ready for Review, size/L

#69 fix: resolve typeError and if condition error
  blockchain/contracts/WavGame.sol
  frontend/src/components/Trade/TradeStart.js
  frontend/src/services/ContractService.js
Labels: 🔍 Ready for Review, size/S

#70 Feat/claim amount copy fixes
  backend/sql/level_setting.sql
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/GameCards/GameCards.tsx
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/LevelCard/LevelCard.tsx
  frontend/src/components/LevelCard/level-card.css
  frontend/src/components/Trade/TradeStart.js
  frontend/src/pages/Artist/Artist.jsx
Labels: 🔍 Ready for Review, size/L

#71 refactor
  backend/MySQL.js
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/hooks/useEarlyBirdCount.js
  frontend/src/services/ContractService.js
Labels: ✅ Approved, size/L

#72 Feat/trade modal copy fixes
  frontend/src/components/GameCards/Level4.jsx
  frontend/src/components/GameCards/Level5.jsx
  frontend/src/components/GameCards/Level6.jsx
  frontend/src/components/Trade/TradeStart.js
Labels: 🔍 Ready for Review, size/M
