Repository liquality/wav-game, pull requests merged in 2023-05, with the labels that each got.

#5 Feat/db onboarding logic
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/v1/classes/User.js
  backend/v1/endpoints.js
  backend/v1/handlers/userHandler.js
  backend/v1/middleware.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/pages/Home.js
  frontend/src/services/NetworkService.js
Labels: 🔍 Ready for Review, size/L

#10 add spinning loader component
  frontend/src/components/Onboarding/LogInOrRegister.js
  frontend/src/components/Onboarding/LoginModal.js
  frontend/src/components/SpinningLoader.js
Labels: size/L

#11 add footer component from final design
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Footer.js
  frontend/src/images/discord.svg
  frontend/src/images/telegram.svg
  frontend/src/images/twitter.svg
Labels: 🔍 Ready for Review, size/L

#12 Feature/dashboard
  frontend/.nvmrc
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/custom.d.ts
  frontend/src/images/Discord.svg
  frontend/src/images/Telegram.svg
  frontend/src/images/Twitter.svg
  frontend/src/images/arrow_right.svg
  frontend/src/images/artist.png
  frontend/src/images/wave_graphic.svg
  frontend/src/index.css
  frontend/src/pages/Dashboard/Dashboard.tsx
  frontend/src/pages/Dashboard/LevelCard.tsx
  frontend/src/pages/Dashboard/NavBar.tsx
  frontend/src/pages/Dashboard/Sidebar.tsx
  frontend/src/pages/Dashboard/dashboard.css
  frontend/tailwind.config.js
Labels: 🔍 Ready for Review, size/XL

#13 Feat/home
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/ArtistGrid.js
  frontend/src/components/Footer.js
  frontend/src/components/Home/HomeNotSignedIn.js
  frontend/src/components/Navbar.js
  frontend/src/components/Onboarding/CreditcardPayment.js
  frontend/src/components/Onboarding/PickArtist.js
  frontend/src/images/arrow_home.svg
  frontend/src/images/arrows_home.svg
  frontend/src/images/artist_text.svg
  frontend/src/images/cd.svg
  frontend/src/images/decorated_line.svg
  frontend/src/images/discord.svg
  frontend/src/images/github.svg
  frontend/src/images/glitter_one.svg
  frontend/src/images/glitter_two.svg
  frontend/src/images/hero_shape_home.svg
  frontend/src/images/how_to_play.svg
  frontend/src/images/johanna_resume28april.pdf
  frontend/src/images/microphone.svg
  frontend/src/images/notes.svg
  frontend/src/images/rewards_tout.svg
  frontend/src/images/small_pink_arrow.svg
  frontend/src/images/sparkle_one.svg
  frontend/src/images/sparkle_two.svg
  frontend/src/images/telegram.svg
  frontend/src/images/twitter.svg
  frontend/src/images/union.svg
  frontend/src/images/winner.svg
  frontend/src/pages/Dashboard/Dashboard.tsx
  frontend/src/pages/Dashboard/NavBar.tsx
  frontend/src/pages/Dashboard/Sidebar.tsx
  frontend/src/pages/Dashboard/UserMenu.js
  frontend/src/pages/Home.js
  frontend/src/utils.ts
  package-lock.json
Labels: size/XXL

#7 add wav-gave contracts
  blockchain/.env.example
  blockchain/.eslintrc.js
  blockchain/.gitignore
  blockchain/.openzeppelin/polygon-mumbai.json
  blockchain/README.md
  blockchain/contracts/WavGame.sol
  blockchain/contracts/WavNFT.sol
  blockchain/contracts/interfaces/IWavGame.sol
  blockchain/contracts/interfaces/IWavNFT.sol
  blockchain/contracts/libraries/Helper.sol
  blockchain/deploy/00_deploy_wav_game.js
  blockchain/hardhat.config.js
  blockchain/package-lock.json
  blockchain/package.json
  blockchain/scripts/deploy.js
  blockchain/test/wavGame.ts
  blockchain/tsconfig.json
Labels: 🔍 Ready for Review, size/XXL
